"""empty message

Revision ID: 07cdb4398df1
Revises: 8decc8e3ba28
Create Date: 2020-06-15 21:33:24.976794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cdb4398df1'
down_revision = '8decc8e3ba28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('borrower', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('checkout_date', sa.String(length=128), nullable=True))
    op.add_column('book', sa.Column('item_caption', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'item_caption')
    op.drop_column('book', 'checkout_date')
    op.drop_column('book', 'borrower')
    # ### end Alembic commands ###
