"""empty message

Revision ID: 4ac7c5b5c31c
Revises: bfb48f3d4390
Create Date: 2020-06-25 16:31:08.887713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac7c5b5c31c'
down_revision = 'bfb48f3d4390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('c_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'c_code')
    # ### end Alembic commands ###
