"""empty message

Revision ID: 8decc8e3ba28
Revises: a39256927c1a
Create Date: 2020-06-11 18:30:44.983399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8decc8e3ba28'
down_revision = 'a39256927c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.String(length=128), nullable=False),
    sa.Column('due_date', sa.String(length=128), nullable=True),
    sa.Column('return_date', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('book', 'isbn',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'isbn',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_table('rental_history')
    # ### end Alembic commands ###
