"""empty message

Revision ID: 8eb3490a6311
Revises: e8ca3001c924
Create Date: 2020-06-25 15:07:33.118081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb3490a6311'
down_revision = 'e8ca3001c924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.String(length=128), nullable=False),
    sa.Column('due_date', sa.String(length=128), nullable=True),
    sa.Column('return_date', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_history')
    # ### end Alembic commands ###
