"""empty message

Revision ID: bfb48f3d4390
Revises: 8eb3490a6311
Create Date: 2020-06-25 15:15:57.889377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb48f3d4390'
down_revision = '8eb3490a6311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('borrower_id', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('borrower_name', sa.String(length=128), nullable=True))
    op.drop_column('book', 'borrower')
    op.add_column('rental_history', sa.Column('user_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_history', 'user_name')
    op.add_column('book', sa.Column('borrower', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('book', 'borrower_name')
    op.drop_column('book', 'borrower_id')
    # ### end Alembic commands ###
