"""empty message

Revision ID: ff72b90028ed
Revises: 068344c9b548
Create Date: 2021-02-10 23:24:32.656775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff72b90028ed'
down_revision = '068344c9b548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'admin')
    # ### end Alembic commands ###
